#Below code has been referred and taken from https://cloud.google.com/kubernetes-engine/docs/concepts/service

apiVersion: v1
kind: Service
metadata:
  name: container1-service
spec:
  type: LoadBalancer
  selector:
    app: container1-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000

