services:
  container1:
    image: tn541193/csci5409-assignment:container1
    ports:
      - '6000:6000'
    volumes:
      - '${PWD}:/app/data'
    networks:
      - CSCI5409_Network
    depends_on:
      - container2

  container2:
    image: tn541193/csci5409-assignment:container2
    ports:
      - '6001:7000'
    volumes:
      - '${PWD}:/app/data'
    networks:
      - CSCI5409_Network

networks:
  CSCI5409_Network:
    driver: bridge

