#Below code has been referred from https://medium.com/google-cloud/kubernetes-110-your-first-deployment-bf123c1d3f8
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: container2-app
  template:
    metadata:
      labels:
        app: container2-app
      annotations:
        cloud.google.com/neg: '{"ingress": true}' 
    spec:
      containers:
        - name: container2
          image: us-east4-docker.pkg.dev/assignment3-k8s/dockerimages/container2
          ports:
            - containerPort: 7000
          volumeMounts:
            - name: assignment3-persistent-volume
              mountPath: /Tanisha_PV_dir
      volumes:
        - name: assignment3-persistent-volume
          persistentVolumeClaim:
            claimName: assignment3-persistent-volume-claim
      imagePullSecrets:
        - name: assignment3-registry-secret


